/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Csrf */
        get: operations["get_csrf_api_csrf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Matters */
        get: operations["list_matters_api_matters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_matters__matter_id__runs_get"];
        put?: never;
        /** Start Run */
        post: operations["start_run_api_matters__matter_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_matters__matter_id__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/runs/{run_id}/attest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attest Run */
        post: operations["attest_run_api_matters__matter_id__runs__run_id__attest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/runs/{run_id}/continue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Continue Run
         * @description Clear a gated-mode checkpoint so the run resumes (mirrors ``mootloop run
         *     continue``; the ``/resume`` route covers operator-paused runs).
         */
        post: operations["continue_run_api_matters__matter_id__runs__run_id__continue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/runs/{run_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Decisions */
        get: operations["get_run_decisions_api_matters__matter_id__runs__run_id__decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/runs/{run_id}/decisions/{decision_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Decision */
        post: operations["resolve_decision_api_matters__matter_id__runs__run_id__decisions__decision_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/runs/{run_id}/gates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Gates */
        get: operations["get_run_gates_api_matters__matter_id__runs__run_id__gates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/runs/{run_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Run Human */
        post: operations["pause_run_human_api_matters__matter_id__runs__run_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/runs/{run_id}/raise-cap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Raise Cap
         * @description Raise a capped run's hard budget cap (absolute ``to_usd`` or ``delta_usd`` over
         *     the current effective cap), reopening it for resumption (plan D5).
         */
        post: operations["raise_cap_api_matters__matter_id__runs__run_id__raise_cap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/runs/{run_id}/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Requests */
        get: operations["get_run_requests_api_matters__matter_id__runs__run_id__requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Run Human */
        post: operations["resume_run_human_api_matters__matter_id__runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run
         * @description Tail the run's journal as Server-Sent Events until it is terminal (plan FE-1).
         *
         *     A GET, so `RateLimitMiddleware` (write-only) never throttles it.
         */
        get: operations["stream_run_api_matters__matter_id__runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/matters/{matter_id}/runs/{run_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Run Internal */
        post: operations["pause_run_internal_internal_matters__matter_id__runs__run_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/matters/{matter_id}/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Run Internal */
        post: operations["resume_run_internal_internal_matters__matter_id__runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Internal Ping
         * @description Liveness probe for the driver/BFF internal path — demonstrates the internal
         *     auth guard is wired and introspectable; carries no matter data.
         */
        get: operations["internal_ping_internal_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/queue/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Internal Queue Next
         * @description Claim the next work item for ``worker_id`` (or 204 when the queue is idle).
         */
        get: operations["internal_queue_next_internal_queue_next_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttestResponse
         * @description A recorded attestation. ``attestation.valid`` carries the state.
         */
        AttestResponse: {
            attestation: components["schemas"]["Attestation"];
            /**
             * Kind
             * @default attested
             * @constant
             */
            kind: "attested";
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
        };
        /**
         * Attestation
         * @description One append-only attestation-manifest record (an attest or an invalidation).
         */
        Attestation: {
            /** Attestation Id */
            attestation_id: string;
            /** Attested At */
            attested_at: string;
            /** Ledger Head Sha256 */
            ledger_head_sha256: string;
            /** Master Sha256 */
            master_sha256: string;
            /** Reason */
            reason?: string | null;
            /** Reviewer */
            reviewer: string;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /**
             * Valid
             * @default true
             */
            valid: boolean;
        };
        /**
         * CsrfToken
         * @description The CSRF token returned alongside the double-submit cookie.
         */
        CsrfToken: {
            /** Csrf Token */
            csrf_token: string;
        };
        /**
         * Decision
         * @description One attorney-gate decision (proposal + optional resolution).
         */
        Decision: {
            /** Decision Id */
            decision_id: string;
            kind: components["schemas"]["DecisionKind"];
            proposal: components["schemas"]["DecisionProposal"];
            /** Request Id */
            request_id?: string | null;
            resolution?: components["schemas"]["DecisionResolution"] | null;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /**
             * Status
             * @default open
             * @enum {string}
             */
            status: "open" | "approved" | "modified" | "denied";
        };
        /**
         * DecisionKind
         * @description The four propose-then-approve attorney gates (plan P-28).
         * @enum {string}
         */
        DecisionKind: "objection_posture" | "privilege_call" | "rfa_disposition" | "unsupported_assertion";
        /**
         * DecisionOption
         * @description One selectable course of action, with the consequence of choosing it.
         */
        DecisionOption: {
            /** Consequence */
            consequence: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /**
         * DecisionProposal
         * @description A persona's proposed call: what it is, why, and the options to choose among.
         */
        DecisionProposal: {
            /** Options */
            options?: components["schemas"]["DecisionOption"][];
            /** Reasoning */
            reasoning: string;
            /** Recommended */
            recommended: string;
            /** Summary */
            summary: string;
        };
        /**
         * DecisionResolution
         * @description The recorded outcome of a decision — how it was resolved and by whom.
         */
        DecisionResolution: {
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "modify" | "deny";
            /** Chosen Key */
            chosen_key?: string | null;
            /** Decided At */
            decided_at: string;
            /** Decided By */
            decided_by: string;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Source
             * @enum {string}
             */
            source: "human" | "policy";
        };
        /**
         * DecisionsResponse
         * @description The run's attorney-gate decisions; each ``decision.status`` is the discriminated
         *     `DecisionStatus` Literal.
         */
        DecisionsResponse: {
            /** Decisions */
            decisions?: components["schemas"]["Decision"][];
            /**
             * Kind
             * @default decisions
             * @constant
             */
            kind: "decisions";
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
        };
        /**
         * GateFail
         * @description The artifact is blocked by this gate — a terminal state for the artifact.
         */
        GateFail: {
            /** Findings */
            findings?: components["schemas"]["GateFinding"][];
            /** Gate */
            gate: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "fail";
        };
        /**
         * GateFinding
         * @description One specific reason a gate reached its verdict (``code`` + human message).
         */
        GateFinding: {
            /** Code */
            code: string;
            /** Locator */
            locator?: string | null;
            /** Message */
            message: string;
        };
        /**
         * GateLedgerResponse
         * @description The run's gate ledger plus the per-turn `GateResult` discriminated union
         *     (`GatePass | GateFail | GatePending`, discriminated on ``status``).
         */
        GateLedgerResponse: {
            /** Blockers */
            blockers?: string[];
            /** Export Ready */
            export_ready: boolean;
            /** Gates */
            gates?: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            /**
             * Kind
             * @default gate_ledger
             * @constant
             */
            kind: "gate_ledger";
            /** Overall */
            overall?: {
                [key: string]: string;
            };
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Turn Gates */
            turn_gates?: (components["schemas"]["GatePass"] | components["schemas"]["GateFail"] | components["schemas"]["GatePending"])[];
        };
        /**
         * GatePass
         * @description The artifact cleared this gate.
         */
        GatePass: {
            /** Findings */
            findings?: components["schemas"]["GateFinding"][];
            /** Gate */
            gate: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "pass";
        };
        /**
         * GatePending
         * @description The gate could not be evaluated yet (e.g. an external check is queued).
         */
        GatePending: {
            /** Findings */
            findings?: components["schemas"]["GateFinding"][];
            /** Gate */
            gate: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "pending";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MatterSummary
         * @description Listing-safe summary of a single matter vault.
         *
         *     `display_name`/`case_number` are the caption strings a human uses to recognize a
         *     matter (court captions are public record, not `MatterText`). `rel_path` is the
         *     vault directory name relative to the matters-root — never an absolute path.
         */
        MatterSummary: {
            /** Case Number */
            case_number: string;
            /** Display Name */
            display_name: string;
            /** Loaded */
            loaded: boolean;
            /** Matter Id */
            matter_id: string;
            /** Rel Path */
            rel_path: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
        };
        /**
         * PauseRequest
         * @description The optional body of a run-pause call; ``reason`` defaults to ``manual``.
         */
        PauseRequest: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * RaiseCapRequest
         * @description The body of a raise-cap call — exactly one of an absolute ``to_usd`` cap or a
         *     ``delta_usd`` increment over the run's current effective cap (plan D5).
         */
        RaiseCapRequest: {
            /** Delta Usd */
            delta_usd?: number | null;
            /** To Usd */
            to_usd?: number | null;
        };
        /**
         * RequestItem
         * @description One served request (or a subpart of one) as a unit of work.
         *
         *     ``subpart`` is ``None`` for a top-level request and a single lowercase letter
         *     for a compound subpart, whose ``text`` is the subpart clause; the parent item
         *     retains the full request text.
         */
        RequestItem: {
            /** Number */
            number: number;
            /** Request Id */
            request_id: string;
            /**
             * Set Number
             * @default 1
             */
            set_number: number;
            /** Source Doc */
            source_doc: string;
            /** Subpart */
            subpart?: string | null;
            /** Text */
            text: string;
        };
        /**
         * RequestsResponse
         * @description The served RFA/discovery request units in scope for the run (matter-scoped).
         */
        RequestsResponse: {
            /**
             * Kind
             * @default requests
             * @constant
             */
            kind: "requests";
            /** Requests */
            requests?: components["schemas"]["RequestItem"][];
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
        };
        /**
         * ResolveRequest
         * @description The body of a decision-resolve call. ``decided_by`` and the timestamp are
         *     server-derived (from the verified principal), never client-supplied.
         */
        ResolveRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "modify" | "deny";
            /** Chosen Key */
            chosen_key?: string | null;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * ResolveResponse
         * @description A resolved decision. ``decision.status`` is the `Literal` discriminated state.
         */
        ResolveResponse: {
            decision: components["schemas"]["Decision"];
            /**
             * Kind
             * @default decision_resolved
             * @constant
             */
            kind: "decision_resolved";
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
        };
        /**
         * RunActionResponse
         * @description The result of a pause/resume/continue/raise-cap call, exposing the run's
         *     resulting `RunStatus` (the discriminated domain state).
         */
        RunActionResponse: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "run_paused" | "run_resumed" | "run_continued" | "cap_raised";
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "finished" | "needs_attention" | "capped" | "needs_decisions" | "checkpoint" | "paused";
        };
        /**
         * RunStatusSummary
         * @description Single-run status envelope for the cockpit (folded from the journal). Exposes
         *     the `RunStatus` Literal; also returned by the start-run wrapper.
         */
        RunStatusSummary: {
            /**
             * Completed Turns
             * @default 0
             */
            completed_turns: number;
            /** Current Stage */
            current_stage?: string | null;
            /**
             * Discarded Turns
             * @default 0
             */
            discarded_turns: number;
            /** Hard Cap Usd */
            hard_cap_usd?: number | null;
            /**
             * Kind
             * @default run_status
             * @constant
             */
            kind: "run_status";
            /**
             * Mode
             * @enum {string}
             */
            mode: "autonomous" | "gated" | "observed";
            /** Open Decisions */
            open_decisions?: string[];
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "finished" | "needs_attention" | "capped" | "needs_decisions" | "checkpoint" | "paused";
            /** Task */
            task?: string | null;
            /**
             * Total Spend Usd
             * @default 0
             */
            total_spend_usd: number;
        };
        /**
         * RunSummary
         * @description Listing-safe summary of one run under a matter vault (derived from the fold).
         */
        RunSummary: {
            /** Current Stage */
            current_stage?: string | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "autonomous" | "gated" | "observed";
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "finished" | "needs_attention" | "capped" | "needs_decisions" | "checkpoint" | "paused";
            /** Task */
            task?: string | null;
            /**
             * Total Spend Usd
             * @default 0
             */
            total_spend_usd: number;
        };
        /**
         * StartRunRequest
         * @description The body of a run-start call; ``task`` and ``mode`` mirror ``mootloop run start``.
         */
        StartRunRequest: {
            /** Mode */
            mode?: ("autonomous" | "gated" | "observed") | null;
            /**
             * Task
             * @default discovery-responses
             */
            task: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_csrf_api_csrf_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfToken"];
                };
            };
        };
    };
    list_matters_api_matters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatterSummary"][];
                };
            };
        };
    };
    list_runs_api_matters__matter_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_matters__matter_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_matters__matter_id__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attest_run_api_matters__matter_id__runs__run_id__attest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    continue_run_api_matters__matter_id__runs__run_id__continue_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_decisions_api_matters__matter_id__runs__run_id__decisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_decision_api_matters__matter_id__runs__run_id__decisions__decision_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
                run_id: string;
                decision_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_gates_api_matters__matter_id__runs__run_id__gates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateLedgerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_run_human_api_matters__matter_id__runs__run_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    raise_cap_api_matters__matter_id__runs__run_id__raise_cap_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RaiseCapRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_requests_api_matters__matter_id__runs__run_id__requests_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_human_api_matters__matter_id__runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_api_matters__matter_id__runs__run_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_run_internal_internal_matters__matter_id__runs__run_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PauseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_internal_internal_matters__matter_id__runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    internal_ping_internal_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    internal_queue_next_internal_queue_next_get: {
        parameters: {
            query: {
                worker_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
